-- CreateEnum
CREATE TYPE "MinistryType" AS ENUM ('PRESIDENT_PASTOR', 'PASTOR', 'DISCIPULADOR', 'LEADER', 'LEADER_IN_TRAINING', 'MEMBER', 'REGULAR_ATTENDEE', 'VISITOR');

-- AlterTable
ALTER TABLE "Ministry" ADD COLUMN     "type" "MinistryType" NOT NULL DEFAULT 'MEMBER';
